//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public int ExperienceId { get; set; }
        public string CompanyName { get; set; }
        public string WorkDate { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
